/*
 * The RPG Engine API
 * Requires The RPG Engine to be running locally.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.RollResult;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ChatApi
 */
@Disabled
public class ChatApiTest {

    private final ChatApi api = new ChatApi();

    /**
     * Post a message to the chat, including roll commands
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void chatPostTest() throws ApiException {
        String body = null;
        RollResult response = api.chatPost(body);
        // TODO: test validations
    }

    /**
     * Post a message to the GM, including roll commands
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void chatPrivatePostTest() throws ApiException {
        String body = null;
        RollResult response = api.chatPrivatePost(body);
        // TODO: test validations
    }

}
