/*
 * The RPG Engine API
 * Requires The RPG Engine to be running locally.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.RollRequest;
import org.openapitools.client.model.RollResult;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DiceApi
 */
@Disabled
public class DiceApiTest {

    private final DiceApi api = new DiceApi();

    /**
     * Get the documentation describing the full capabilities of running a dice command
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void rollGetTest() throws ApiException {
        String response = api.rollGet();
        // TODO: test validations
    }

    /**
     * Roll a dice and get the result (Doesn&#39;t show in chat)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void rollPostTest() throws ApiException {
        RollRequest rollRequest = null;
        RollResult response = api.rollPost(rollRequest);
        // TODO: test validations
    }

}
