/**
 * The RPG Engine API
 * Requires The RPG Engine to be running locally.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Vector3 from './Vector3';

/**
 * The CreateFx model module.
 * @module model/CreateFx
 * @version 1.0.0
 */
class CreateFx {
    /**
     * Constructs a new <code>CreateFx</code>.
     * @alias module:model/CreateFx
     */
    constructor() { 
        
        CreateFx.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CreateFx</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateFx} obj Optional instance to populate.
     * @return {module:model/CreateFx} The populated <code>CreateFx</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateFx();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('position')) {
                obj['position'] = Vector3.constructFromObject(data['position']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreateFx</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreateFx</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // validate the optional field `position`
        if (data['position']) { // data not null
          Vector3.validateJSON(data['position']);
        }

        return true;
    }


}



/**
 * The name of the click effect.
 * @member {String} name
 */
CreateFx.prototype['name'] = undefined;

/**
 * @member {module:model/Vector3} position
 */
CreateFx.prototype['position'] = undefined;






export default CreateFx;

