/**
 * The RPG Engine API
 * Requires The RPG Engine to be running locally.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Prop from './Prop';

/**
 * The PagedResponseOfProp model module.
 * @module model/PagedResponseOfProp
 * @version 1.0.0
 */
class PagedResponseOfProp {
    /**
     * Constructs a new <code>PagedResponseOfProp</code>.
     * @alias module:model/PagedResponseOfProp
     */
    constructor() { 
        
        PagedResponseOfProp.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PagedResponseOfProp</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PagedResponseOfProp} obj Optional instance to populate.
     * @return {module:model/PagedResponseOfProp} The populated <code>PagedResponseOfProp</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PagedResponseOfProp();

            if (data.hasOwnProperty('count')) {
                obj['count'] = ApiClient.convertToType(data['count'], 'Number');
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], [Prop]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PagedResponseOfProp</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PagedResponseOfProp</code>.
     */
    static validateJSON(data) {
        if (data['data']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['data'])) {
                throw new Error("Expected the field `data` to be an array in the JSON data but got " + data['data']);
            }
            // validate the optional field `data` (array)
            for (const item of data['data']) {
                Prop.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Number} count
 */
PagedResponseOfProp.prototype['count'] = undefined;

/**
 * @member {Array.<module:model/Prop>} data
 */
PagedResponseOfProp.prototype['data'] = undefined;






export default PagedResponseOfProp;

