/**
 * The RPG Engine API
 * Requires The RPG Engine to be running locally.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import RollRequest from '../model/RollRequest';
import RollResult from '../model/RollResult';

/**
* Dice service.
* @module api/DiceApi
* @version 1.0.0
*/
export default class DiceApi {

    /**
    * Constructs a new DiceApi. 
    * @alias module:api/DiceApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the rollGet operation.
     * @callback module:api/DiceApi~rollGetCallback
     * @param {String} error Error message, if any.
     * @param {String} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get the documentation describing the full capabilities of running a dice command
     * @param {module:api/DiceApi~rollGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link String}
     */
    rollGet(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/text'];
      let returnType = 'String';
      return this.apiClient.callApi(
        '/Roll', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the rollPost operation.
     * @callback module:api/DiceApi~rollPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/RollResult} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Roll a dice and get the result (Doesn't show in chat)
     * @param {module:model/RollRequest} rollRequest Dice roll request
     * @param {module:api/DiceApi~rollPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/RollResult}
     */
    rollPost(rollRequest, callback) {
      let postBody = rollRequest;
      // verify the required parameter 'rollRequest' is set
      if (rollRequest === undefined || rollRequest === null) {
        throw new Error("Missing the required parameter 'rollRequest' when calling rollPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = RollResult;
      return this.apiClient.callApi(
        '/Roll', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
