/*
 * The RPG Engine API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
// uncomment below to import models
//using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing CampaignsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class CampaignsApiTests : IDisposable
    {
        private CampaignsApi instance;

        public CampaignsApiTests()
        {
            instance = new CampaignsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CampaignsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' CampaignsApi
            //Assert.IsType<CampaignsApi>(instance);
        }

        /// <summary>
        /// Test CampaignsCampaignDelete
        /// </summary>
        [Fact]
        public void CampaignsCampaignDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string campaign = null;
            //instance.CampaignsCampaignDelete(campaign);
        }

        /// <summary>
        /// Test CampaignsCampaignMapsGet
        /// </summary>
        [Fact]
        public void CampaignsCampaignMapsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string campaign = null;
            //var response = instance.CampaignsCampaignMapsGet(campaign);
            //Assert.IsType<PagedResponseOfString>(response);
        }

        /// <summary>
        /// Test CampaignsCampaignOpenPost
        /// </summary>
        [Fact]
        public void CampaignsCampaignOpenPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string campaign = null;
            //instance.CampaignsCampaignOpenPost(campaign);
        }

        /// <summary>
        /// Test CampaignsCampaignPost
        /// </summary>
        [Fact]
        public void CampaignsCampaignPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string campaign = null;
            //instance.CampaignsCampaignPost(campaign);
        }

        /// <summary>
        /// Test CampaignsGet
        /// </summary>
        [Fact]
        public void CampaignsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.CampaignsGet();
            //Assert.IsType<PagedResponseOfString>(response);
        }
    }
}
