/*
 * The RPG Engine API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing PagedResponseOfString
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PagedResponseOfStringTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PagedResponseOfString
        //private PagedResponseOfString instance;

        public PagedResponseOfStringTests()
        {
            // TODO uncomment below to create an instance of PagedResponseOfString
            //instance = new PagedResponseOfString();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PagedResponseOfString
        /// </summary>
        [Fact]
        public void PagedResponseOfStringInstanceTest()
        {
            // TODO uncomment below to test "IsType" PagedResponseOfString
            //Assert.IsType<PagedResponseOfString>(instance);
        }

        /// <summary>
        /// Test the property 'Count'
        /// </summary>
        [Fact]
        public void CountTest()
        {
            // TODO unit test for the property 'Count'
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
    }
}
