/*
 * The RPG Engine API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing PropCharacterData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PropCharacterDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PropCharacterData
        //private PropCharacterData instance;

        public PropCharacterDataTests()
        {
            // TODO uncomment below to create an instance of PropCharacterData
            //instance = new PropCharacterData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PropCharacterData
        /// </summary>
        [Fact]
        public void PropCharacterDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" PropCharacterData
            //Assert.IsType<PropCharacterData>(instance);
        }

        /// <summary>
        /// Test the property 'ShowHelmet'
        /// </summary>
        [Fact]
        public void ShowHelmetTest()
        {
            // TODO unit test for the property 'ShowHelmet'
        }

        /// <summary>
        /// Test the property 'Parts'
        /// </summary>
        [Fact]
        public void PartsTest()
        {
            // TODO unit test for the property 'Parts'
        }

        /// <summary>
        /// Test the property 'Colors'
        /// </summary>
        [Fact]
        public void ColorsTest()
        {
            // TODO unit test for the property 'Colors'
        }
    }
}
