/*
 * The RPG Engine API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing PropCanvasData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PropCanvasDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PropCanvasData
        //private PropCanvasData instance;

        public PropCanvasDataTests()
        {
            // TODO uncomment below to create an instance of PropCanvasData
            //instance = new PropCanvasData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PropCanvasData
        /// </summary>
        [Fact]
        public void PropCanvasDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" PropCanvasData
            //Assert.IsType<PropCanvasData>(instance);
        }

        /// <summary>
        /// Test the property 'VarVersion'
        /// </summary>
        [Fact]
        public void VarVersionTest()
        {
            // TODO unit test for the property 'VarVersion'
        }

        /// <summary>
        /// Test the property 'ShowTitle'
        /// </summary>
        [Fact]
        public void ShowTitleTest()
        {
            // TODO unit test for the property 'ShowTitle'
        }

        /// <summary>
        /// Test the property 'Sliders'
        /// </summary>
        [Fact]
        public void SlidersTest()
        {
            // TODO unit test for the property 'Sliders'
        }

        /// <summary>
        /// Test the property 'ShowStatuses'
        /// </summary>
        [Fact]
        public void ShowStatusesTest()
        {
            // TODO unit test for the property 'ShowStatuses'
        }

        /// <summary>
        /// Test the property 'Statuses'
        /// </summary>
        [Fact]
        public void StatusesTest()
        {
            // TODO unit test for the property 'Statuses'
        }
    }
}
