/*
 * The RPG Engine API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing Vector4
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class Vector4Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Vector4
        //private Vector4 instance;

        public Vector4Tests()
        {
            // TODO uncomment below to create an instance of Vector4
            //instance = new Vector4();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Vector4
        /// </summary>
        [Fact]
        public void Vector4InstanceTest()
        {
            // TODO uncomment below to test "IsType" Vector4
            //Assert.IsType<Vector4>(instance);
        }

        /// <summary>
        /// Test the property 'X'
        /// </summary>
        [Fact]
        public void XTest()
        {
            // TODO unit test for the property 'X'
        }

        /// <summary>
        /// Test the property 'Y'
        /// </summary>
        [Fact]
        public void YTest()
        {
            // TODO unit test for the property 'Y'
        }

        /// <summary>
        /// Test the property 'Z'
        /// </summary>
        [Fact]
        public void ZTest()
        {
            // TODO unit test for the property 'Z'
        }

        /// <summary>
        /// Test the property 'W'
        /// </summary>
        [Fact]
        public void WTest()
        {
            // TODO unit test for the property 'W'
        }
    }
}
