/*
 * The RPG Engine API
 * Requires The RPG Engine to be running locally.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.openapitools.client.model.Color;
import org.openapitools.client.model.Vector2;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Atmosphere
 */
public class AtmosphereTest {
    private final Atmosphere model = new Atmosphere();

    /**
     * Model tests for Atmosphere
     */
    @Test
    public void testAtmosphere() {
        // TODO: test Atmosphere
    }

    /**
     * Test the property 'version'
     */
    @Test
    public void versionTest() {
        // TODO: test version
    }

    /**
     * Test the property 'lightRotation'
     */
    @Test
    public void lightRotationTest() {
        // TODO: test lightRotation
    }

    /**
     * Test the property 'lightColour'
     */
    @Test
    public void lightColourTest() {
        // TODO: test lightColour
    }

    /**
     * Test the property 'ambientColor'
     */
    @Test
    public void ambientColorTest() {
        // TODO: test ambientColor
    }

    /**
     * Test the property 'enableFog'
     */
    @Test
    public void enableFogTest() {
        // TODO: test enableFog
    }

    /**
     * Test the property 'fogColour'
     */
    @Test
    public void fogColourTest() {
        // TODO: test fogColour
    }

    /**
     * Test the property 'fogDensity'
     */
    @Test
    public void fogDensityTest() {
        // TODO: test fogDensity
    }

    /**
     * Test the property 'fogHeight'
     */
    @Test
    public void fogHeightTest() {
        // TODO: test fogHeight
    }

    /**
     * Test the property 'clouds'
     */
    @Test
    public void cloudsTest() {
        // TODO: test clouds
    }

    /**
     * Test the property 'abyss'
     */
    @Test
    public void abyssTest() {
        // TODO: test abyss
    }

    /**
     * Test the property 'table'
     */
    @Test
    public void tableTest() {
        // TODO: test table
    }

    /**
     * Test the property 'tableColor'
     */
    @Test
    public void tableColorTest() {
        // TODO: test tableColor
    }

    /**
     * Test the property 'skybox'
     */
    @Test
    public void skyboxTest() {
        // TODO: test skybox
    }

    /**
     * Test the property 'rainAmount'
     */
    @Test
    public void rainAmountTest() {
        // TODO: test rainAmount
    }

    /**
     * Test the property 'snowAmount'
     */
    @Test
    public void snowAmountTest() {
        // TODO: test snowAmount
    }

}
