/*
 * The RPG Engine API
 * Requires The RPG Engine to be running locally.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Color
 */
public class ColorTest {
    private final Color model = new Color();

    /**
     * Model tests for Color
     */
    @Test
    public void testColor() {
        // TODO: test Color
    }

    /**
     * Test the property 'r'
     */
    @Test
    public void rTest() {
        // TODO: test r
    }

    /**
     * Test the property 'g'
     */
    @Test
    public void gTest() {
        // TODO: test g
    }

    /**
     * Test the property 'b'
     */
    @Test
    public void bTest() {
        // TODO: test b
    }

    /**
     * Test the property 'a'
     */
    @Test
    public void aTest() {
        // TODO: test a
    }

}
